version: "3"

services:
  server:
    build: 
      context: ./
      dockerfile: ./docker/vcmp/Dockerfile
    volumes:
      - ./src/plugins:/home/appuser/plugins:ro
      - ./src/server.cfg:/home/appuser/server.cfg:ro
      - ./src/store:/home/appuser/store:ro
    ports:
      - 8192:8192/udp
    networks:
      - default
    depends_on:
      - mysql
      - redis
      
  mysql:
    image: mysql:5.7-debian
    environment:
      MYSQL_DATABASE: 'vicerp'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7.0.0-alpine
    networks:
      - default
    
networks:
  default:
    driver: bridge
